### ISSUE TITLE
Using tiny font with Webpack

### ISSUE THREAD

**Issue by joseasv** [darkwebdev/tinyfont.js#3]
Using ``` import { initFont, font } from 'tinyfont/font-tiny' ``` shows Module not found: Error: Can't resolve './dist/tinyfont-tiny.min'.

I had to rename tinyfont-font-tiny.min.js file of the dist folder to tinyfont-tiny.min.js

**Comment by darkwebdev** [comment]
thanks man! fixed, published as v1.3.2
